---
title: "R Notebook"
output: html_notebook
---

```{r}
# Load tidyverse
library(tidyverse)
```

```{r}
# Very untidy table
readxl::read_excel("datasets/bad-table-psych.xlsx")
```

```{r}
# Clean unityd table
readxl::read_excel(
  "datasets/bad-table-psych.xlsx", 
  skip = 2, 
  n_max = 12, .name_repair = "universal"
) %>% 
  select(-c(Name, Birthday, Comment)) %>% 
  select(where(\(x) !(all(is.na(x)) | all(x == "")))) %>% 
  rename_with(\(x) str_to_lower(x)) %>% 
  rename_with((\(x) str_replace_all(x, "\\.+", "_"))) %>% 
  rename(
    test_time = "_9",
    rec_lang = language_11) %>% 
  separate_wider_delim(
    test_reaction, 
    delim = "=", 
    names = c("test", "reaction")
  ) %>% 
  mutate(
    gender = str_extract(gender, "^.",),
    language_native = 
      case_when(
        str_detect(language_4, "^[gG]") ~ "deu",
        str_detect(language_4, "^[fF]") ~ "fra"
      )
  ) %>% 
  rowid_to_column() %>% 
  separate_longer_delim(stai, delim = ",") %>% 
  separate_wider_delim(
    stai, 
    delim = "=", 
    names = c("stai_key", "stai_val")
  ) %>% 
  mutate(
    stai_val = as.integer(stai_val),
    stai_key = str_c("stai_", trimws(stai_key))) %>% 
  relocate(rowid, starts_with("stai"), .before = everything()) %>% 
  pivot_wider(names_from = stai_key, values_from = stai_val)
```



```{r}
# A tibble with tribble
(clean_data <- 
  tribble(
    ~family, ~patient,
    "F1", 101,
    "F1", 102,
    "F2", 201
  )
 )
```
#### Basic rearrangements

Splitting values - tidyr::separate()
```{r}
# Two variables in the same column, key-value pairs
(patient1 <- 
   tribble(
  ~subject_id, ~gender_age,
  1001, "m-34",      
  1002, "f-63",      
  1003, "m-57",      
  1004, "f-42",      
  1005, "m-58",      
  1006, "f-59",
   )
)
```

```{r}
# Separate to different variables with delimiter
patient1 %>% 
  separate_wider_delim(
    gender_age, 
    delim = "-", 
    names = c("gender", "age")
  )
```

```{r}
# Separate to different variables with delimiter
patient1 %>% 
  separate_wider_position(
    gender_age, widths = c(gender = 1, 1, age = 2)
  )
```

```{r}
# Two variables in the same column, no separator
(patient2 <- 
   tribble(
  ~subject_id, ~gender_age,
  1001, "m34",      
  1002, "f63",      
  1003, "m57",      
  1004, "f42",      
  1005, "m58",      
  1006, "f59",
   )
)
```

```{r}
# Separate to different variables with position
patient2 %>% 
  separate_wider_position(
    gender_age, widths = c(gender = 1, age = 2)
  )
```

Splitting and collating - separate() and unite()
```{r}
# Input tibble
(data_value <-
  tibble(
    year = c(2015, 2014, 2014),
    month = c(11, 2, 4),
    day = c(23, 1, 30),
    value = c("high", "low", "low")
    )
 )
```

```{r}
# Unite
(date_unite <- 
   data_value %>% 
   unite("date", year:day, sep = "-" ))
```

```{r}
# Separate to columns with delimiter
date_unite %>% 
  separate_wider_delim(
    date, 
    delim = "-", 
    names = c("year", "month", "day")
  )
```

```{r}
# Parsing dates with Lubridate functions
# A gift from your collaborators
(visit_times <- tribble(
  ~subject, ~visit_date,
  1, "01/07/2001",
  2, "01.MAY.2012",
  3, "12-07-2015",
  4, "4/5/14",
  5, "12. Jun 1999"
))
```

```{r}
# Lubridate to the rescue!
visit_times %>% 
  mutate(date = lubridate::dmy(visit_date))
```

```{r}
# Separate rows with multiple entries 
# Multiple values per cell
# Note the incoherent white space and separators
(patient_df <- tibble(
    subject_id = 1001:1003, 
    visit_id = c("1,2, 3", "1;2", "1"),
    measured = c("9,0; 11", "11, 3", "12"))
 )
```

```{r}
# With separate_longer_delim use stringr::regex for multiple delimiters
# No option to convert types
patient_df %>% 
  separate_longer_delim(c(visit_id, measured), delim = regex("[,;]")) 
```

```{r}
# The original 'separate_rows' works like this
(patient_separate <- 
   patient_df %>% 
   separate_rows(
     c(visit_id, measured), 
     convert = TRUE)
)
```

```{r}
# Fill all combinations with complete()
patient_separate %>% 
  complete(subject_id, visit_id)
```

```{r}
# Note that the 'nesting' is not required here
patient_separate %>% 
  complete(subject_id, nesting(visit_id))
```

```{r}
# Fill all combinations with complete() and replace NAs
# Be careful with replacing NAs with zeros in real data!
patient_separate %>% 
  complete(subject_id, visit_id, fill = list(measured = 0))
```